Repository BerriAI/litellm, pull requests merged in 2025-09, with the labels that each got.

#14028 Add Volcengine embedding module with handler and transformation logic
  docs/my-website/docs/providers/volcano.md
  litellm/__init__.py
  litellm/llms/volcengine/__init__.py
  litellm/llms/volcengine/chat/transformation.py
  litellm/llms/volcengine/common_utils.py
  litellm/llms/volcengine/embedding/__init__.py
  litellm/llms/volcengine/embedding/handler.py
  litellm/llms/volcengine/embedding/transformation.py
  litellm/main.py
  litellm/router.py
  litellm/utils.py
  model_prices_and_context_window.json
  tests/test_litellm/llms/volcengine/__init__.py
  tests/test_litellm/llms/volcengine/embedding/__init__.py
  tests/test_litellm/llms/volcengine/test_volcengine.py
  tests/test_litellm/llms/volcengine/test_volcengine_embedding.py
  tests/test_litellm/test_utils.py
Labels: changes requested

#14262 feat: Add support for reasoning_effort='minimal' for Gemini models
  litellm/constants.py
  litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py
  tests/llm_translation/test_gemini.py
Labels: awaiting: user response

#14299 Doc Updates 9-5-25
  docs/my-website/docs/proxy/access_control.md
  docs/my-website/docs/proxy/admin_ui_sso.md
  docs/my-website/docs/proxy/load_balancing.md
  docs/my-website/docs/proxy/user_management_heirarchy.md
  docs/my-website/img/admin_settings_ui_theme.png
  docs/my-website/img/admin_settings_ui_theme_logo.png
Labels: changes requested

#14542 fix: recompute filters after deleting an MCP Server
  ui/litellm-dashboard/src/components/mcp_tools/mcp_servers.tsx
Labels: awaiting: user response, changes requested

#14534 fix: improve response api handling and cold storage configuration
  litellm/litellm_core_utils/litellm_logging.py
  litellm/responses/litellm_completion_transformation/session_handler.py
  tests/test_litellm/litellm_core_utils/test_litellm_logging.py
  tests/test_litellm/responses/litellm_completion_transformation/test_session_handler.py
Labels: awaiting: user response, changes requested

#14557 Implement AWS Bedrock CountTokens API support
  litellm/llms/bedrock/count_tokens/handler.py
  litellm/llms/bedrock/count_tokens/transformation.py
  litellm/proxy/pass_through_endpoints/llm_passthrough_endpoints.py
  tests/proxy_unit_tests/test_proxy_token_counter.py
  tests/test_litellm/llms/bedrock/count_tokens/test_bedrock_count_tokens_transformation.py
Labels: awaiting: user response

#14587 Fix: Streaming tool call index assignment for multiple tool calls
  litellm/types/utils.py
  tests/litellm_utils_tests/test_utils.py
Labels: awaiting: user response

#15000 [Performance] Reduce complexity of `InMemoryCache.evict_cache` from O(n*log(n)) to O(log(n))
  litellm/caching/in_memory_cache.py
  tests/test_litellm/caching/test_in_memory_cache.py
  tests/test_litellm/litellm_core_utils/specialty_caches/test_dynamic_logging_cache.py
Labels: changes requested
