Repository BerriAI/litellm, pull requests merged in 2025-07, with the labels that each got.

#12303 Fix DeepEval logging format for failure events
  litellm/integrations/deepeval/deepeval.py
Labels: codex

#12304 Fix credentials CLI test
  tests/test_litellm/proxy/client/cli/test_credentials_commands.py
Labels: codex

#9980 fix(watsonx): IBM Watsonx - use correct parameter name for tool choice
  litellm/llms/watsonx/chat/transformation.py
  tests/llm_translation/test_optional_params.py
  tests/local_testing/test_function_calling.py
Labels: stale

#12507 Fix/gemini api key environment variable support
  litellm/llms/gemini/common_utils.py
  litellm/llms/gemini/google_genai/transformation.py
  litellm/llms/gemini/realtime/transformation.py
  litellm/main.py
  litellm/proxy/pass_through_endpoints/llm_passthrough_endpoints.py
  litellm/utils.py
  tests/test_litellm/llms/gemini/test_gemini_client_setup.py
  tests/test_litellm/proxy/test_spend_log_cleanup.py
Labels: missing testing
