Repository BerriAI/litellm, pull requests merged in 2025-08, with the labels that each got.

#12169 Add digitalocean provider
  README.md
  docs/my-website/docs/providers/gradient_ai.md
  docs/my-website/sidebars.js
  litellm/__init__.py
  litellm/constants.py
  litellm/litellm_core_utils/get_llm_provider_logic.py
  litellm/llms/gradient_ai/chat/transformation.py
  litellm/main.py
  litellm/types/utils.py
  litellm/utils.py
  model_prices_and_context_window.json
  tests/litellm/llms/gradient_ai/chat/test_gradient_ai_chat_transformation.py
  ui/litellm-dashboard/out/assets/logos/gradientai.svg
  ui/litellm-dashboard/src/components/add_model/provider_specific_fields.tsx
  ui/litellm-dashboard/src/components/provider_info_helpers.tsx
Labels: awaiting: user response, changes requested

#13308 Feat/sambanova embeddings
  docs/my-website/docs/providers/sambanova.md
  litellm/__init__.py
  litellm/litellm_core_utils/get_supported_openai_params.py
  litellm/llms/sambanova/common_utils.py
  litellm/llms/sambanova/embedding/handler.py
  litellm/llms/sambanova/embedding/transformation.py
  litellm/main.py
  litellm/model_prices_and_context_window_backup.json
  litellm/utils.py
  tests/test_litellm/llms/sambanova/tests_sambanova_embedding_transformation.py
Labels: changes requested

#13783 Update Baseten LiteLLM integration
  cookbook/liteLLM_Baseten.ipynb
  docs/my-website/docs/providers/baseten.md
  litellm/__init__.py
  litellm/constants.py
  litellm/litellm_core_utils/get_llm_provider_logic.py
  litellm/litellm_core_utils/get_supported_openai_params.py
  litellm/llms/baseten.py
  litellm/llms/baseten/chat.py
  litellm/main.py
  litellm/utils.py
  tests/test_litellm/llms/baseten/chat/test_baseten_completions.py
Labels: changes requested

#13916 feat: multiple images in openai images/edits endpoint
  docs/my-website/docs/image_edits.md
  litellm/images/main.py
  tests/image_gen_tests/test_image_edits.py
  ui/litellm-dashboard/src/components/chat_ui.tsx
  ui/litellm-dashboard/src/components/chat_ui/llm_calls/image_edits.tsx
Labels: awaiting: user response

#13160 Update Pangea Guardrail to support new AIDR endpoint
  litellm/proxy/guardrails/guardrail_hooks/pangea/pangea.py
  tests/test_litellm/proxy/guardrails/guardrail_hooks/test_pangea.py
Labels: awaiting: user response, changes requested
